let coffee: Sprite = null
let amSleepy = true
if (amSleepy) {
    coffee = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . d . . . . d . . . . . . 
        . . . . d . . . d d . . . . . . 
        . . . . . d . . d . . . . e . . 
        . 1 1 e e d e e e e 1 1 . . . . 
        . 1 1 e e e e e e e 1 1 . . . . 
        . 1 1 e e e e e e e 1 1 1 1 1 . 
        . 1 1 e e e e e e e 1 1 . 1 1 . 
        . 1 1 1 1 1 1 1 1 1 1 1 . 1 1 . 
        . 1 1 1 1 1 1 1 1 1 1 1 . 1 1 . 
        . 1 1 1 1 1 1 1 1 1 1 1 . 1 1 . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
        . 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
        . 1 1 1 1 1 1 1 1 1 1 1 . . . . 
        . 1 1 1 1 1 1 1 1 1 1 1 . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Food)
} else {
    coffee = sprites.create(img`
        ........................
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff..........
        .ffefbf44fbfeff.........
        .fee41fddf14eef.........
        fdfeeddddd4eff..........
        fbffee444edd4e..........
        fbf4f2222edde...........
        fcf.f22cfcee............
        .ff.f44fdc4f............
        ....fffddfff............
        .....fddfff.............
        ....fddf.fff............
        ...ffdff.fff............
        ...ffff.................
        ...fff..................
        ........................
        ........................
        ........................
        `, SpriteKind.Player)
}
